Update triggers.yml

diff --git a/.github/workflows/triggers.yml b/.github/workflows/triggers.yml
--- a/.github/workflows/triggers.yml
+++ b/.github/workflows/triggers.yml
@@ -1,17 +1,54 @@
-name: triggers-test
+name: percy-test-status
 
 on:
   workflow_run:
     workflows: ["push-to-master"]
     types: 
       - completed
+  pull_request:
+    types:
+      - unlabeled
+      - labeled
 
 jobs:
-  job-1:
+  percy-test-status:
+    if: false == contains(github.event.pull_request.labels.*.name, 'check-percy-results-before-merge') || github.event.workflow_run.conclusion == 'success'
     runs-on: ubuntu-latest
+    env:
+     TRIGGER_EVENT_NAME: ${{ github.event_name }}
+     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
     steps:
-      - name: Step1
-        run: |
-          echo ${{ github.event.workflow_run.head_commit.id  }}
-          echo ${{ github.event.workflow_run.conclusion }}
+      - name: Enable merge if no percy checks pending
+        shell: bash
+        run: |  
+          echo 'my trigger is: ' $TRIGGER_EVENT_NAME
+          echo 'my event is: ' ${{ github.event }}
+
+           if [ $TRIGGER_EVENT_NAME=='pull_request' ]; then
+            sha=${{ github.event.pull_request.head.sha }}
+            prNumber=${{ github.event.number }}
+          else
+            sha=${{ github.event.workflow_run.head_commit.id }}
+            prNumber=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/search/issues\?q\="${sha}" | jq '. | .items' | jq '.[]' | jq '.number')
+          fi
+
+          echo 'my commit is:' "${sha}"         
+          echo 'my PR is:' "${prNumber}"
+          
+          numberSuccessCheckSuites=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/rosahealth/rosa/commits/"${sha}"/check-suites | jq '.check_suites' | jq '.[] | select(.app.slug=="github-actions") |.conclusion' | jq  'select(. == "success")' | jq -s '.' | jq length)
+          numberPercyLabels=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/rosahealth/rosa/issues/"${prNumber}" | jq '.labels' | jq '.[] | .name' | jq 'select(. == "check-percy-results-before-merge")' | jq -s '.' | jq length)
+
+          echo 'successful checks:' $numberSuccessCheckSuites
+          echo 'percy labels:' $numberPercyLabels
+         
+          # we set the workflow to pass if there is no percy labels set on the PR and the other 2 GH Actions Workflows status-checks have reported success
+          if [ $numberSuccessCheckSuites -ge 2 ] && [ $numberPercyLabels -eq 0 ]; then
+            echo "build-and-test & build-and-deploy are successful, no percy label is set"
+            exit 0
+          else
+            echo "1 or more workflows are failed or Percy label is set"
+            exit 1
+          fi
+             
           
